apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/argo-cd.git"
    targetRevision: HEAD
    path: application/helm/speedtest
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
